name: Test PR

on: 
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  Build:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build.yml
    secrets: inherit  
    with:
      prNumber: ${{ github.event.pull_request.number }}
      runE2ETests: ${{ contains(github.event.pull_request.labels.*.name, 'Checks/Run with UI Tests') }}
